name: Pull-Request-Quality-Check

on:
  pull_request:
    branches: [ "main" ]
    types: [ opened, synchronize, reopened ]  # Runs on PR creation, updates, and reopens

permissions:
  contents: read  # Allows reading repository contents
  checks: write  # Allows writing test reports
  pull-requests: write  # Allows reporting results on PRs

jobs:
  build:
    uses: ./.github/workflows/build-template.yml
    secrets: inherit
    with:
      node-version: '24'
      run-tests: true
      run-sonar-analysis: true
      sonar-qualitygate-wait: true  # Wait for SonarQube quality gate and fail build if it fails
